server:
  port: 8088
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
  mapper-locations: classpath:com/lq/*/mapper/xml/*.xml		#mapper的位置
spring:
  application:
    name: smartWardrobe
  datasource:
    type: com.zaxxer.hikari.HikariDataSource     #HikariDataSource 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smartWardrobe_db?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8